#!/bin/bash

# Alle Plugins besorgen
if [ ! -d plugins ]; then 
    mkdir plugins; 
fi

for line in $(cat plugins.cfg | grep -v "^\s*#"); do
	method=$(echo $line | awk -F"::" '{print $1}')
	uri=$(echo $line | awk -F"::" '{print $2}')
	target=$(echo $line | awk -F"::" '{print $3}')
	format=$(echo $line | awk -F"::" '{print $4}')
	
	if [ $method == "git" ] && [ ! -d plugins/$target ]; then
	    echo "--------------"
	    echo -n "Getting plugin $target with method git..."
	    git clone $uri plugins/$target
	fi	

	if [ $method == "wget" ] && [ ! -d plugins/$target ]; then 
	    echo "--------------"
	    echo -n "Getting plugin $target with method wget..."
	    wget $uri -O plugins/$target.download
	    case $format in
	    "tgz")
		pushd .
	        mkdir plugins/$target
		cd plugins/$target && tar -xzf ../$target.download --strip=1
		rm ../$target.download
		popd
	    ;;
	    "zip")
		pushd .
		cd plugins
		extract=$(unzip -l $target.download | awk '{print $4}' | awk -F/ '{print $1}' | grep -v "^Name" | grep -v "^---" | grep -v "^$" | uniq)
		unzip $target.download
		mv $extract $target
		rm $target.download
		popd
	    ;;
	    esac
	    echo " done."
	fi
done 
	


