# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 20 Mar 2018 09:51:57 +0000
*               @ALL          0
*               @user         8
