<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Tue, 20 Mar 2018 09:51:57 +0000
 */
$conf['title'] = 'OpenSchulportfolio';
$conf['lang'] = 'de';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
